### ISSUE TITLE
Release POD

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-ios#10]
When doing a lint on the pod spec I get an error:

```
$ pod spec lint ably.podspec

 -> ably (0.7.0)
    - WARN  | [iOS]  SocketRocket/SocketRocket/SRWebSocket.m:923:55: warning: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'size_t' (aka 'unsigned long') [-Wshorten-64-to-32]
    - WARN  |  SocketRocket/SocketRocket/SRWebSocket.m:1606:32: warning: unused function 'log_queue' [-Wunused-function]
    - WARN  | [iOS]  SocketRocket/SocketRocket/SRWebSocket.m:127:20: warning: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'CC_LONG' (aka 'unsigned int') [-Wshorten-64-to-32]
    - WARN  | [iOS]  SocketRocket/SocketRocket/SRWebSocket.m:464:209: warning: values of type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead [-Wformat]
    - WARN  | [iOS]  SocketRocket/SocketRocket/SRWebSocket.m:533:135: warning: values of type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead [-Wformat]
    - WARN  | [iOS]  SocketRocket/SocketRocket/SRWebSocket.m:568:74: warning: implicit conversion loses integer precision: 'NSInteger' (aka 'long') to 'UInt32' (aka 'unsigned int') [-Wshorten-64-to-32]
    - WARN  | [iOS]  SocketRocket/SocketRocket/SRWebSocket.m:879:92: warning: values of type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead [-Wformat]
    - WARN  | [iOS]  SocketRocket/SocketRocket/SRWebSocket.m:1463:38: warning: implicit conversion loses integer precision: 'NSInteger' (aka 'long') to 'int' [-Wshorten-64-to-32]
    - WARN  | [iOS]  SocketRocket/SocketRocket/SRWebSocket.m:1673:12: warning: implicit conversion loses integer precision: 'long' to 'int32_t' (aka 'int') [-Wshorten-64-to-32]
    - WARN  | [iOS]  SocketRocket/SocketRocket/base64.c:183:10: warning: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'int' [-Wshorten-64-to-32]
    - WARN  |  ably/ably-ios/ARTMsgPackEncoder.m:63:17: warning: method 'decodeError:' in protocol 'ARTEncoder' not implemented [-Wprotocol]
    - NOTE  |  ably/ably-ios/ARTEncoder.h:37:1: note: method 'decodeError:' declared here

Analyzed 1 podspec.

[!] The spec did not pass validation.
```

Also, once this is fixed, can you advise how I can publish this pod?

**Comment by mattheworiordan** [comment]
@thevixac please see above?

**Comment by mattheworiordan** [comment]
@ricardopereira can you confirm this is resolved?

**Comment by ricardopereira** [comment]
Still broken. Removing all the current warnings from code will do it.

**Comment by mattheworiordan** [comment]
> Removing all the current warnings from code will do it.

What is involved in that?

**Comment by ricardopereira** [comment]
The `pod spec lint` validates the `podspec` and warn you of any errors that occur. The warnings are the same from what we have on the code. There is a option `--allow-warnings` that validates even if warnings are present but I prefer to fix all the warnings.

**Comment by mattheworiordan** [comment]
Yes, definitely

**Comment by ricardopereira** [comment]
#213 does some changes about this issue.
Now, the lint result is:

```
➜  ably-ios git:(master) ✗ pod spec lint Ably.podspec

[!] The spec did not pass validation, due to 1 error.
➜  ably-ios git:(master) ✗ pod spec lint Ably.podspec --verbose

    Ably (0.8.0) - Analyzing on iOS 8.0 platform.
  Preparing

Analyzing dependencies

Fetching external sources
-> Fetching podspec for `Ably` from `/Users/ricardopereira/Repositories/Whitesmith/ably-ios/Ably.podspec`

Resolving dependencies of

Comparing resolved specification to the sandbox manifest
  A Ably
  A SwiftWebSocket

Downloading dependencies

-> Installing Ably (0.8.0)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/ably/ably-ios.git
     /var/folders/s0/n37l1z0x4jv26v1cfkt9514m0000gn/T/d20160213-44778-x0hrcl --single-branch --depth
     1 --branch 0.8.0
     Cloning into '/var/folders/s0/n37l1z0x4jv26v1cfkt9514m0000gn/T/d20160213-44778-x0hrcl'...
     warning: Could not find remote branch 0.8.0 to clone.
     fatal: Remote branch 0.8.0 not found in upstream origin

[!] Error installing Ably
 -> Ably (0.8.0)
    - ERROR | [iOS] unknown: Encountered an unknown error ([!] /usr/bin/git clone https://github.com/ably/ably-ios.git /var/folders/s0/n37l1z0x4jv26v1cfkt9514m0000gn/T/d20160213-44778-x0hrcl --single-branch --depth 1 --branch 0.8.0

Cloning into '/var/folders/s0/n37l1z0x4jv26v1cfkt9514m0000gn/T/d20160213-44778-x0hrcl'...
warning: Could not find remote branch 0.8.0 to clone.
fatal: Remote branch 0.8.0 not found in upstream origin
) during validation.
```
It is an expected error.
Basically, the tag `0.8.0` is missing.

**Comment by mattheworiordan** [comment]
> Basically, the tag 0.8.0 is missing.

Ok, we should hopefully be in a position to do a 0.8.0 tag release I expect, once we are confident the API won't have expected breaking changes. @tcard do you think we are at this point, especially considering https://github.com/ably/docs/pull/87?

**Comment by tcard** [comment]
@mattheworiordan Well, I don't know what is to be expected form a 0.8.0 tag release. It surely doesn't implement the 0.8 full spec (including ably/docs#87) yet. The API, on superficial terms, _should_ be totally compatible with the 0.8 spec after merging #204, so if you think that's enough...

**Comment by mattheworiordan** [comment]
@tcard based on semver, I'd like to ensure that any updates from the point we hit `0.8.0` don't break the existing API i.e. if we add more overloaded methods, new methods to objects, add attributes, then that's not breaking.  But if we are aware of any breaking changes to the API in the current state, then I'd prefer we address that before a `0.8` release.  What is your view on that?

**Comment by tcard** [comment]
@mattheworiordan Semantic versioning API guarantees don't kick in before 1.0, so OK, we can make a "soft promise" about it at this point (after #204), I think.

**Comment by mattheworiordan** [comment]
> Semantic versioning API guarantees don't kick in before 1.0
I was not aware of that, our next release should then be `1.0` instead of `0.9`.  I will raise an issue

**Comment by mattheworiordan** [comment]
@ricardopereira we have decided that given the fix for 
https://github.com/CocoaPods/trunk.cocoapods.org/issues/172#issuecomment-197915929 could take a long time, we're going to publish as `AblyRealtime`.  Please update the Pod for master, tell me when done, and I will push this to Cocoapods.

**Comment by mattheworiordan** [comment]
FYI, I published it successfully:

```
$ pod trunk push AblyRealtime.podspec
Updating spec repo `master`

CocoaPods 1.0.0.beta.6 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Validating podspec
 -> AblyRealtime (0.8.0-beta.3)

Updating spec repo `master`

CocoaPods 1.0.0.beta.6 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

  - Data URL: https://raw.githubusercontent.com/CocoaPods/Specs/b0ffd47dc16bc5b72d350301e7f84b601e00acf3/Specs/AblyRealtime/0.8.0-beta.3/AblyRealtime.podspec.json
  - Log messages:
    - March 18th, 19:07: Push for `AblyRealtime 0.8.0-beta.3' initiated.
    - March 18th, 19:07: Push for `AblyRealtime 0.8.0-beta.3' has been pushed (2.168428523 s).
```

However, oddly it seems that Cocoapods is having an issue now, see https://cocoapods.org/?q=Ably, the old Ably module is now showing and AblyRealtime is missing, then weirdly going to https://cocoapods.org/pods/ably gives a 500, yet going to https://cocoapods.org/pods/AblyRealtime redirects to https://www.ably.io.  WTF is going on?

**Comment by ricardopereira** [comment]
What the mess!
Well, _AblyRealtime_ is available https://github.com/CocoaPods/Specs/blob/master/Specs/AblyRealtime/0.8.0-beta.3/AblyRealtime.podspec.json and I try it with:

```
pod 'AblyRealtime', '= 0.8.0-beta.3'
```

and it works.

**Comment by orta** [comment]
The old one is showing because I classed it as un-deleted for you, I've un-done that, next time the search is re-index'd it should be removed.

**Comment by mattheworiordan** [comment]
Thanks @orta. I assume we'll follow the issue progress until you guys have addressed the Github issue so that we can publish it as Ably?  Thanks again.

**Comment by ricardopereira** [comment]
What about this one? Will `AblyRealtime` pod be renamed to `Ably`?

**Comment by mattheworiordan** [comment]
@ricardopereira if we can yes, can you try?

**Comment by ricardopereira** [comment]
@mattheworiordan I tried again and the usual error occurs: `[!] {"name"=>["is already taken"]}`.
@orta Could you please take a look?

---

branch: `test-rename-ably-pod`
tag: `0.8.6`
log:

```
... (redacted)

** BUILD SUCCEEDED **

 -> Ably (0.8.6)
    - WARN  | xcodebuild:  msgpack/Pod/Classes/MessagePackParser+Streaming.m:22:18: warning: designated initializer should only invoke a designated initializer on 'super' [-Wobjc-designated-initializers]
    - NOTE  | xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/usr/include/objc/NSObject.h:60:1: note: method marked as designated initializer of the class here

opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established
<- "POST /api/v1/pods?allow_warnings=true HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.0.1\r\nAuthorization: Token a9dd38babd855c64fc6d84da2209c868\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 670\r\n\r\n"
<- "{\"name\":\"Ably\",\"version\":\"0.8.6\",\"summary\":\"iOS client for Ably\",\"description\":\"iOS client library for ably.io, the realtime messaging service, written in Objective-C and ready for Swift 2.0.\",\"homepage\":\"https://www.ably.io\",\"license\":{\"type\":\"Apache 2.0\",\"file\":\"LICENSE\"},\"authors\":{\"Ably\":\"support@ably.io\"},\"source\":{\"git\":\"https://github.com/ably/ably-ios.git\",\"tag\":\"0.8.6\"},\"requires_arc\":true,\"social_media_url\":\"https://twitter.com/ablyrealtime\",\"documentation_url\":\"https://www.ably.io/documentation\",\"platforms\":{\"ios\":\"8.0\"},\"source_files\":\"Source/*.{h,m}\",\"module_map\":\"Source/Ably.modulemap\",\"dependencies\":{\"SocketRocket\":[\"0.5.1\"],\"msgpack\":[\"0.1.8\"]}}\n"
-> "HTTP/1.1 422 \r\n"
-> "Date: Fri, 02 Sep 2016 17:28:23 GMT\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 39\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Server: thin 1.6.2 codename Doc Brown\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 39 bytes...
-> "{\"error\":{\"name\":[\"is already taken\"]}}"
read 39 bytes
Conn keep-alive
```

**Comment by orta** [comment]
I've marked "Ably" as not deleted, if you can't push now it's because you don't have access via trunk for that email. 👍

**Comment by ricardopereira** [comment]
@orta Unfortunately, I got the same error: `[!] {"name"=>["is already taken"]}`.

**Comment by ricardopereira** [comment]
`pod trunk me` has `ably`

```
  - Name:     Ricardo Pereira
  - Email:    ricardopereira.eu@gmail.com
  - Since:    May 30th, 2015 21:02
  - Pods:
    - ably
... (redacted)
```

@orta Maybe is something related with the char case, could be? Is it possbile to rename it to capitalised?

**Comment by orta** [comment]
Yeah looks like the case check is [on purpose](https://github.com/CocoaPods/trunk.cocoapods.org/blob/master/spec/functional/api/pods_controller_spec.rb#L124) - I can change the case in the db, but I'm not 100% sure of all the ramifications, though, as  I guess no-one is using the pod yet so it shouldn't break existing installations

**Comment by orta** [comment]
done

**Comment by ricardopereira** [comment]
Success 🙌 
@orta thank you.

**Comment by ricardopereira** [comment]
https://cocoapods.org/?q=Ably

**Comment by mattheworiordan** [comment]
Thanks @orta, we all really appreciate your help :)
